In [1]:
import numpy as np


In [2]:

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) / 9 # slept, study
y = np.array(([92], [86], [89]), dtype=float) / 100 # marks


In [3]:

class NN:
    def __init__(self):
        self.W1 = np.random.randn(2, 3)
        self.W2 = np.random.randn(3, 1)
    def forward(self, X):
        self.z2 = 1 / (1 + np.exp(-np.dot(X, self.W1)))
        return 1 / (1 + np.exp(-np.dot(self.z2, self.W2)))
    def backward(self, X, y, o):
        o_delta = (y - o) * o * (1 - o)
        self.W2 += np.dot(self.z2.T, o_delta)
        self.W1 += np.dot(X.T, np.dot(o_delta, self.W2.T) * self.z2 * (1 - self.z2))


In [4]:

NN = NN()
for _ in range(1000):
    o = NN.forward(X)
    NN.backward(X, y, o)
    print("\nInput:\n", X, "\nActual Output:\n", y, "\nPredicted Output:\n", o, "\nLoss:", np.mean(np.square(y - o)))



Input:
 [[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]] 
Actual Output:
 [[0.92]
 [0.86]
 [0.89]] 
Predicted Output:
 [[0.69135679]
 [0.68289127]
 [0.6875093 ]] 
Loss: 0.04154923465041632

Input:
 [[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]] 
Actual Output:
 [[0.92]
 [0.86]
 [0.89]] 
Predicted Output:
 [[0.7180297 ]
 [0.70797243]
 [0.71365687]] 
Loss: 0.031667093718880455

Input:
 [[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]] 
Actual Output:
 [[0.92]
 [0.86]
 [0.89]] 
Predicted Output:
 [[0.73947364]
 [0.7281474 ]
 [0.73465592]] 
Loss: 0.024702219333949168

Input:
 [[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]] 
Actual Output:
 [[0.92]
 [0.86]
 [0.89]] 
Predicted Output:
 [[0.75698514]
 [0.74463965]
 [0.75179239]] 
Loss: 0.01966106617713839

Input:
 [[0.22222222 1.        ]
 [0.11111111 0.55555556]
 [0.33333333 0.66666667]] 
Actual Output:
 [[0.92]
 [0.86]
 [0.89]] 
Pr